baseURL = "https://chaitanyassr.netlify.com"
languageCode = "en-us"
title = "chaitanyassr portfolio"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "CHINUON"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact" 
			aside     = "GitHub"

	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "HI I AM CHAITANYA"
		subtitle   = "I am a game developer and a JAMStack geek. I use Unreal engine 4 and Godot for game development. I love Hugo."
		buttonText = "Hire me"


	# About section
	[params.about]
		headline    = "hyaku-nigiri"
		description = "I am Chaitanya. I love to build new things. I am a quick learner and a heavy [GitHub](https://github.com/Chaitanyassr) user. I am a founder of [Chinuon-studio](https://github.com/Chinuon) an open source organisation. You can get to the site to download games by clicking on the Chinuon icon at the top. Want to know my skills as a developer? check out my resume!"
		buttonText  = "resume"


	# Service section
	[params.services]
		headline = "At your service"
         des = "I love to write in my free time. Check out my [blog](https://chinustorychaitanya.wordpress.com/author/chinustorychaitanya/)(for poems and songs) and [quora](https://www.quora.com/profile/Chaitanya-216). apart from that I also did my graduation in fine-arts from Chandigarh kala kendra. I also do singing, dancing and theater. You can check out my [instagram](https://www.instagram.com/1st_incommand/), [twitter](https://twitter.com/Chinu282828777) and [linkedin](https://www.linkedin.com/in/kumar-chaitanya-a04a13147/)."
 
        [[params.services.list]]
			icon = "fa-paper-plane"
			title = "Ready to Ship"
			description = "You can use this theme as is, or you can make changes!"

    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Want to check out my cool projects. Here's the link of my GitHub account"

		[params.aside.button]
			text = "GitHub"
			icon = "fa-github"
			link = "https://github.com/Chaitanyassr"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Want to hire me as a freelancer or ready to start your next project with me? That's great! Give me a call or send me an email!"
		phone = "857-289-6685"
		email = "chaitanyas0101@gmail.com, chinuon@circlepanda.io"
 
	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
